'use client';

import { ArrowLeft, ArrowRight, Bird, Maximize, X } from 'lucide-react';
import { useEffect, useState } from 'react';

const slides = [
  { time: '1:00', type: 'cover', title: 'Mining Sparrow Nest Patterns', subtitle: 'Descriptive and predictive methods used in the Eurasian Tree Sparrow study' },
  { time: '1:15', type: 'split', kicker: 'RESEARCH SCOPE', title: 'Dataset, targets and mining methods', left: ['657 building records from China', 'Features: height, width, altitude and average noise', 'Climate: temperature, precipitation and wind', 'Classification target: Lower 1–4 vs Higher 5+', 'Regression target: exact NestCount', 'Spatial split: 501 train / 156 holdout by ID'], right: ['Descriptive mining', 'Statistics · Apriori · FP-Growth · K-means · Average-linkage hierarchical clustering · PCA visualization', 'Predictive mining', 'Decision Tree · Random Forest · Logistic Regression · Gaussian Naive Bayes · Linear Regression · Dummy baselines'] },
  { time: '1:00', type: 'workflow', kicker: 'NOTEBOOK WORKFLOW', title: 'Complete analysis pipeline', steps: [['01','Load, audit and split','Read the GB18030 CSV. Validate numeric values, dimensions, counts, rain and wind. Retain all 657 rows. GroupShuffleSplit by ID gives 501 train and 156 holdout with zero group overlap.'],['02','Describe the variables','Compute count, mean, standard deviation, quartiles and range for seven features plus NestCount. Plot 20-bin distributions, selected scatterplots and a Pearson correlation heatmap.'],['03','Mine association rules','Convert each feature to training-tertile Low, Medium or High. Run Apriori and FP-Growth with support ≥ 0.10 and max length 3. Generate rules at confidence ≥ 0.60 and keep nest-target rules with lift > 1.'],['04','Find building profiles','Standardize all seven features. Compare K-means and average-linkage hierarchical clustering for k=2…6 using silhouette and Calinski-Harabasz scores. Select K-means k=5 and visualize saved assignments with PCA.'],['05','Train predictive models','Use five-fold StratifiedGroupKFold by ID. Compare 5 classifiers using accuracy, precision, recall, F1 and AUC. Compare 5 regressors using MAE, RMSE and R². Select Decision Trees by F1 and MAE.'],['06','Final test and export','Refit both selected trees on all 501 training rows. Test once on 156 spatial holdout rows. Export predictions, confusion matrix, regression plot, joblib models and metadata for the live simulation.']] },
  { time: '1:00', type: 'detail', kicker: 'DATA PREPARATION', title: 'The notebook prepares one model table', rows: [['Load','Read GB18030 CSV and preserve Building# and ID as strings'],['Audit','Check structure, missing values, exact duplicates, zero nests and density recalculations'],['Validation','Numeric coercion, finite values, positive dimensions, integer non-negative NestCount, non-negative rain and wind'],['Cleaning result','657 original, 0 flagged, 657 retained'],['Features','BuildingHeight, BuildingWidth, Altitude, AveNoise, temp, prec, win'],['Targets','Classification: >4 nests. Regression: exact NestCount'],['Spatial split','GroupShuffleSplit by ID, test_size=0.20, random_state=42. Result: 501 train, 156 holdout, 0 group overlap']] },
  { time: '0:45', type: 'detail', kicker: 'OUTLIER REVIEW', title: 'Extreme values were reviewed, not automatically removed', rows: [['How we checked','20-bin histograms for all seven features and NestCount; scatterplots for BuildingHeight, AveNoise and precipitation against NestCount'],['Observed range','NestCount minimum 1, Q1 2, median 4, Q3 7, maximum 50'],['Validity rules','Reject nonnumeric or infinite values, nonpositive dimensions, invalid counts, negative precipitation or wind'],['Result','0 rows failed validation; all 657 records were retained'],['What was not used','No IQR fence, Z-score threshold, winsorization or automatic outlier deletion appears in the notebook'],['Reason','An extreme but valid ecological observation can contain information. Removing it requires domain evidence, not only its distance from the mean'],['Model protection','Trees use max_depth=3 and min_samples_leaf=10; final spatial holdout exposes weak generalization']] },
  { time: '1:30', type: 'methods', kicker: 'DESCRIPTIVE · 01', title: 'Start by describing the sample', methods: [['Descriptive statistics', 'Mean, median, standard deviation, min/max and distributions', 'Understand scale, spread and unusual values before modeling.'], ['Key observation', 'Median = 4 nests · Mean = 5.74 nests', 'The higher mean and maximum of 50 show a right-skewed target.']] },
  { time: '2:00', type: 'methods', kicker: 'DESCRIPTIVE · 02', title: 'Association rules find conditions that occur together', methods: [['Apriori', 'Candidate-based frequent itemset search', 'min_support 0.10 and maximum itemset length 3.'], ['FP-Growth', 'Frequency-tree itemset search', 'Same settings; itemsets and support values verified equal.'], ['Rule filtering', 'confidence ≥ 0.60, NestCountGroup as the only consequent', 'Remove target items from antecedents, then keep lift > 1.'], ['Result', '217 frequent itemsets from each algorithm', 'Apriori 0.0067 s and FP-Growth 0.0104 s on 501 records.']] },
  { time: '1:00', type: 'detail', kicker: 'ASSOCIATION SETTINGS', title: 'Discretization boundaries from the training data', rows: [['BuildingHeight','Low ≤ 18, Medium ≤ 24, High > 24'],['BuildingWidth','Low ≤ 40, Medium ≤ 60, High > 60'],['Altitude','Low ≤ 784, Medium ≤ 1179.21, High > 1179.21'],['AveNoise','Low ≤ 49, Medium ≤ 54, High > 54'],['Temperature','Low ≤ 16.19, Medium ≤ 17.08, High > 17.08'],['Precipitation','Low ≤ 43, Medium ≤ 59.67, High > 59.67'],['Wind','Low ≤ 2.43, Medium ≤ 2.53, High > 2.53']] },
  { time: '1:30', type: 'quote', kicker: 'HOW TO READ ONE RULE', title: 'Low altitude + high precipitation → Higher nest count', stat: '74.3%', body: 'of matching training records had five or more nests.', note: 'Support 15.6% · Lift 1.65 · Association does not prove cause and effect.' },
  { time: '2:00', type: 'chart', kicker: 'DESCRIPTIVE · 03', title: 'Clustering finds similar building profiles', image: '/figures/cluster_pca.png', bullets: ['StandardScaler prevents large-unit features from dominating.', 'K-means and average-linkage hierarchical clustering were compared for k = 2…6.', 'K-means k = 5 had its best silhouette score: 0.267.', 'PCA is only the 2D visualization—the clusters use all seven features.'] },
  { time: '1:00', type: 'detail', kicker: 'CLUSTER COMPARISON', title: 'K-means k = 5 gives the strongest balanced solution', rows: [['K-means k=2','Silhouette 0.247, cluster sizes 236–265'],['K-means k=3','Silhouette 0.264, cluster sizes 102–205'],['K-means k=4','Silhouette 0.256, cluster sizes 76–164'],['K-means k=5','Silhouette 0.267, cluster sizes 51–156 · Selected'],['K-means k=6','Silhouette 0.256, cluster sizes 57–119'],['Hierarchical result','Higher k produced clusters as small as one record, so profiles were less balanced']] },
  { time: '2:00', type: 'detail', kicker: 'CLUSTER PROFILES', title: 'The five clusters represent distinct building and environmental settings', rows: [['Cluster 0 · Moderate-altitude, noisy','125 records (25.0%). Height 22.97, width 48.82, altitude 789.88, noise 54.72, temperature 16.80, precipitation 58.55, wind 2.57. Mean nests 5.31.'],['Cluster 1 · Warm, wet, low-altitude','76 records (15.2%). Height 44.48, width 41.88, altitude 53.92, noise 52.59, temperature 20.03, precipitation 68.17, wind 2.43. Mean nests 13.58.'],['Cluster 2 · High-altitude, dry, wide','156 records (31.1%). Height 21.23, width 59.28, altitude 1269.50, noise 49.27, temperature 15.75, precipitation 28.98, wind 2.65. Mean nests 3.78.'],['Cluster 3 · Highest-altitude, cool, low-wind','93 records (18.6%). Height 24.51, width 48.62, altitude 1480.95, noise 50.00, temperature 15.50, precipitation 53.55, wind 1.92. Mean nests 2.86.'],['Cluster 4 · Very tall buildings','51 records (10.2%). Height 79.25, width 52.14, altitude 881.14, noise 52.71, temperature 16.72, precipitation 56.19, wind 2.44. Mean nests 5.65.'],['Interpretation','NestCount was excluded from K-means and compared afterward. Silhouette 0.267 indicates overlap, so these are descriptive profiles rather than sharply separated natural classes.']] },
  { time: '1:00', type: 'detail', kicker: 'TRAINING STRATEGY', title: 'Model selection happens before the final test', rows: [['Step 1','Keep spatial groups separate in 501 training and 156 holdout records'],['Step 2','Compare models with five-fold group-aware cross-validation'],['Classification choice','Select the highest mean F1 score'],['Regression choice','Select the lowest mean MAE'],['Step 3','Fit the selected Decision Trees on all training records'],['Step 4','Evaluate once on the untouched spatial holdout']] },
  { time: '2:15', type: 'models', kicker: 'PREDICTIVE · CLASSIFICATION', title: 'Predict Lower vs Higher nest count', target: 'Lower: 1–4 nests  ·  Higher: 5+ nests', image:'/figures/classification_comparison.png', models: [['Decision Tree', 'Gini, max_depth=3, min_samples_leaf=10', '0.630 F1'], ['Random Forest', '200 trees, depth 5, leaf minimum 5', '0.620 F1'], ['Logistic Regression', 'StandardScaler pipeline, max_iter=2000', '0.596 F1'], ['Gaussian Naive Bayes', 'Numeric probabilistic comparison', '0.564 F1']], note: 'Decision Tree selected by highest mean cross-validation F1. OOF predictions and tree rules were exported.' },
  { time: '1:00', type: 'detail', kicker: 'DECISION TREE RULES', title: 'The selected classifier uses four features', rows: [['Root split','Altitude ≤ 1107'],['Low-altitude branch','Altitude ≤ 434.20 predicts Higher; otherwise BuildingWidth ≤ 50.50 predicts Lower'],['High-altitude branch','Temperature ≤ 16.11 leads to Lower'],['Remaining branch','Precipitation ≤ 43.08 or > 43.08 both lead to Lower leaves'],['Interpretation','The shallow tree is readable, but its final holdout AUC is only 0.505'],['Saved evidence','decision_tree.png, decision_tree_rules.txt and decision_tree_oof_predictions.csv']] },
  { time: '1:00', type: 'detail', kicker: 'CLASSIFICATION CV', title: 'All classification metrics', rows: [['Decision Tree','Accuracy 0.655, Precision 0.601, Recall 0.702, F1 0.630, AUC 0.698'],['Random Forest','Accuracy 0.684, Precision 0.687, Recall 0.628, F1 0.620, AUC 0.734'],['Logistic Regression','Accuracy 0.668, Precision 0.646, Recall 0.602, F1 0.596, AUC 0.750'],['Gaussian Naive Bayes','Accuracy 0.670, Precision 0.701, Recall 0.569, F1 0.564, AUC 0.732'],['Majority baseline','Accuracy 0.548, F1 0.000, AUC 0.500'],['Selection','Decision Tree because the notebook selects by mean F1, not accuracy or AUC']] },
  { time: '2:00', type: 'models', kicker: 'PREDICTIVE · REGRESSION', title: 'Predict the exact NestCount', target: 'Numeric target: number of nests', image:'/figures/regression_diagnostics.png', models: [['Decision Tree', 'Nonlinear feature conditions', '2.824 MAE'], ['Random Forest', 'Average many trees', '2.827 MAE'], ['Linear Regression', 'Linear relationship baseline', '3.209 MAE'], ['Dummy Mean', 'Always predicts training mean', '3.708 MAE']], note: 'Decision Tree selected by lowest mean cross-validation MAE.' },
  { time: '1:00', type: 'detail', kicker: 'REGRESSION CV', title: 'All regression metrics', rows: [['Decision Tree','MAE 2.824, RMSE 4.354, R² 0.227 · Selected'],['Random Forest','MAE 2.827, RMSE 4.291, R² 0.219'],['Linear Regression','MAE 3.209, RMSE 4.525, R² 0.145'],['Median baseline','MAE 3.388, RMSE 5.336, R² -0.094'],['Mean baseline','MAE 3.708, RMSE 5.277, R² -0.116'],['Selection','Decision Tree has the lowest mean MAE by a narrow 0.003 margin over Random Forest']] },
  { time: '1:30', type: 'evaluation', kicker: 'TRAINING & FINAL TEST', title: 'The holdout result changes the conclusion', image:'/figures/final_confusion_matrix.png', metrics: [['501 / 156', 'Spatial train / holdout'], ['5-fold', 'Group-aware CV'], ['0.505', 'Holdout ROC-AUC'], ['4.095', 'Holdout regression MAE'], ['3.190', 'Mean baseline MAE']], body: 'Patterns were found inside the study sample, but prediction did not generalize reliably to held-out spatial groups.' },
  { time: '1:00', type: 'detail', kicker: 'FINAL HOLDOUT', title: 'Selected models on unseen spatial groups', rows: [['Classification Decision Tree','Accuracy 0.551, Precision 0.579, Recall 0.750, F1 0.653, ROC-AUC 0.505'],['Classification baseline','Accuracy 0.436, F1 0.000, ROC-AUC 0.500'],['Regression Decision Tree','MAE 4.095, RMSE 5.698, R² -0.575'],['Regression mean baseline','MAE 3.190, RMSE 4.550, R² -0.005'],['Regression median baseline','MAE 3.276, RMSE 4.953, R² -0.190'],['Meaning','The regression tree performs worse than both simple holdout baselines']] },
  { time: 'DEMO', type: 'demo', kicker: 'LIVE MODEL LAB', title: 'Test the saved models and mining outputs' },
  { time: '1:00', type: 'end', kicker: 'CONCLUSION', title: 'Describe confidently. Predict cautiously.', bullets: ['Descriptive statistics, association rules and clustering found patterns in the 501 training records.', 'Decision Trees won the notebook selection rules: highest classification F1 and lowest regression MAE.', 'The 156-record spatial holdout showed weak transfer to new groups.', 'The notebooks export CSV evidence, figures, two fitted joblib models and metadata for the simulation.', 'Limitations: China-only data, no breeding-success measure and no reliable external prediction yet.'] },
] as const;

export default function Presentation() {
  const [current, setCurrent] = useState(0);
  const [full, setFull] = useState(false);
  const move = (step: number) => setCurrent((value) => Math.max(0, Math.min(slides.length - 1, value + step)));
  useEffect(() => { const key = (e: KeyboardEvent) => { if (e.key === 'ArrowRight' || e.key === ' ') move(1); if (e.key === 'ArrowLeft') move(-1); }; addEventListener('keydown', key); return () => removeEventListener('keydown', key); }, []);
  const kicker = 'kicker' in slides[current] ? slides[current].kicker : '';
  const section = /CONCLUSION/.test(kicker) ? 'Conclusion' : /FINAL|EVALUATION|LIVE/.test(kicker) ? 'Evaluation' : /PREDICTIVE|TRAINING|CLASSIFICATION|REGRESSION|DECISION/.test(kicker) ? 'Predictive' : /DESCRIPTIVE|ASSOCIATION|CLUSTER|RULE/.test(kicker) ? 'Descriptive' : 'Study';
  return <main className={full ? 'presentation fullscreen' : 'presentation'} data-section={section}>
    <header><div className="logo"><Bird size={20}/> SparrowScope</div><nav>{['Study','Descriptive','Predictive','Evaluation','Conclusion'].map(name=><span className={section===name?'active':''} key={name}>{name}</span>)}</nav><button onClick={() => setFull(!full)} aria-label={full ? 'Exit focus mode' : 'Enter focus mode'}>{full ? <X/> : <Maximize/>}</button></header>
    <aside className="slide-index"><strong>{section}</strong><span>{String(current+1).padStart(2,'0')}</span><i/><small>{slides[current].time}</small></aside>
    <Slide slide={slides[current]}/>
    <footer><div className="progress"><i style={{width:`${((current + 1) / slides.length) * 100}%`}}/></div><button onClick={() => move(-1)} disabled={current === 0}><ArrowLeft/></button><span>{String(current + 1).padStart(2,'0')} / {slides.length} · {slides[current].time}</span><button onClick={() => move(1)} disabled={current === slides.length - 1}><ArrowRight/></button></footer>
  </main>;
}

function Slide({ slide }: { slide: (typeof slides)[number] }) {
  if (slide.type === 'cover') return <section className="slide cover"><div><span>DATA MINING PROJECT · 2026</span><h1>{slide.title}</h1><p>{slide.subtitle}</p></div><img src="/illustrations/sparrow-hero.png" alt="Eurasian Tree Sparrow in an urban habitat"/></section>;
  return <section className={`slide ${slide.type}`}><div className="heading"><span>{slide.kicker}</span><h1>{slide.title}</h1>{'target' in slide && <p>{slide.target}</p>}</div>
    {slide.type === 'split' && <div className="split-grid"><ul>{slide.left.map(x=><li key={x}>{x}</li>)}</ul><div>{[0,2].map(i=><article key={i}><strong>{slide.right[i]}</strong><p>{slide.right[i+1]}</p></article>)}</div></div>}
    {slide.type === 'methods' && <div className="method-list">{slide.methods.map(([name,what,why])=><article key={name}><span>{name}</span><strong>{what}</strong><p>{why}</p></article>)}</div>}
    {slide.type === 'detail' && <div className="detail-table">{slide.rows.map(([label,value],i)=><div key={label}><i>{String(i+1).padStart(2,'0')}</i><strong>{label}</strong><span>{value}</span></div>)}</div>}
    {slide.type === 'workflow' && <><FlowDiagram/><div className="workflow-list">{slide.steps.map(([n,name,text])=><article key={n}><span>{n}</span><div><strong>{name}</strong><p>{text}</p></div></article>)}</div></>}
    {slide.type === 'quote' && <div className="rule"><strong>{slide.stat}</strong><p>{slide.body}</p><small>{slide.note}</small></div>}
    {slide.type === 'chart' && <div className="chart-grid"><img src={slide.image} alt="PCA projection of the five K-means clusters"/><ul>{slide.bullets.map(x=><li key={x}>{x}</li>)}</ul></div>}
    {slide.type === 'models' && <><ModelDiagram regression={slide.title.includes('exact')}/><div className="evidence-grid"><div className="model-table">{slide.models.map(([name,why,result])=><div key={name}><strong>{name}</strong><span>{why}</span><b>{result}</b></div>)}</div><img src={slide.image} alt={`${slide.title} notebook chart`}/></div><p className="takeaway">{slide.note}</p></>}
    {slide.type === 'evaluation' && <><ModelDiagram evaluation/><div className="evaluation-grid"><div className="metrics">{slide.metrics.map(([value,label])=><div key={label}><strong>{value}</strong><span>{label}</span></div>)}</div><img src={slide.image} alt="Final classification confusion matrix"/></div><blockquote>{slide.body}</blockquote></>}
    {slide.type === 'demo' && <ModelDemo/>}
    {slide.type === 'end' && <><ul className="conclusion-list">{slide.bullets.map(x=><li key={x}>{x}</li>)}</ul><div className="resource-links"><a href="https://sparrow-nest-data-mining.streamlit.app/" target="_blank" rel="noreferrer">Open model simulator</a><a href="/downloads/Sparrow_Cluster_Profiles.pptx" download>Download PowerPoint</a><a href="/downloads/Eurasian_Tree_Sparrow_Data_Mining_Project.pdf" target="_blank" rel="noreferrer">Open project book</a></div></>}
  </section>;
}

function FlowDiagram(){return <div className="flow-diagram" aria-label="Notebook execution flow">{[['Raw CSV','657 rows'],['Clean & split','501 / 156'],['Describe','Statistics'],['Mine','Rules + clusters'],['Predict','10 models'],['Evaluate','Spatial holdout']].map(([name,detail],i)=><div key={name}><article><strong>{name}</strong><span>{detail}</span></article>{i<5&&<b>→</b>}</div>)}</div>}

function ModelDiagram({regression=false,evaluation=false}:{regression?:boolean;evaluation?:boolean}){const nodes=evaluation?[['Selected trees','Fit 501 rows'],['Spatial holdout','156 rows'],['Compare','Models vs baseline'],['Conclusion','Generalization']]:[['7 features','Input'],[regression?'5 regressors':'5 classifiers','Group CV'],[regression?'Lowest MAE':'Highest F1','Selection'],['Decision Tree','Best model']];return <div className="model-diagram">{nodes.map(([name,detail],i)=><div key={name}><article><span>{detail}</span><strong>{name}</strong></article>{i<nodes.length-1&&<b>→</b>}</div>)}</div>}

type SimulationResult = { error?:string; position?:number; totalRecords?:number; building?:string; id?:string; split?:string; record?:Record<string,number>; actualNestCount?:number|null; edited?:boolean; bestModels?:{classifier:string;class:string;probability:number;regressor:string;estimatedCount:number}; cluster?:number; clusterProfile?:{name:string;characteristics:string;records:number}; associationRules?:{rule:string;confidence:number;lift:number}[] };
function ModelDemo(){
  const [result,setResult]=useState<SimulationResult|null>(null); const [busy,setBusy]=useState(false); const [stage,setStage]=useState(-1); const [viewStage,setViewStage]=useState(0); const [position,setPosition]=useState(1); const [values,setValues]=useState<Record<string,number>>({});
  async function run(random=false,edited=false){ setBusy(true); setStage(0); try{ const response=await fetch('http://localhost:8000',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mode:'simulation',position:random?null:position-1,values:edited?values:undefined})}); const data=await response.json() as SimulationResult; for(let i=1;i<6;i++){await new Promise(resolve=>setTimeout(resolve,180));setStage(i)} setResult(data); if(!data.error&&data.position!==undefined){setPosition(data.position+1);if(!edited&&data.record)setValues(data.record);setViewStage(edited?3:0)} }catch{ setResult({error:'Start the Python API: venv/bin/python api/main.py'}); }finally{setBusy(false)} }
  const stages=['Sample real record','Discretize and match rules','Standardize seven features','Assign K-means cluster','Run best classifier','Run best regressor'];
  const views=['Dataset nature','Association','Clustering','Prediction','Knowledge'];
  return <div className="simulation"><div className="sim-left"><div className="sim-head"><p>Choose any dataset row, edit its seven features, then explore the notebook stages.</p><div className="sim-actions"><label>Dataset row <input type="number" min="1" max="657" value={position} onChange={e=>setPosition(Number(e.target.value))}/></label><button onClick={()=>run(false,false)} disabled={busy}>Load row</button><button className="secondary" onClick={()=>run(true,false)} disabled={busy}>Random</button></div></div>{result?.record&&<div className="sim-inputs">{Object.entries(values).map(([name,value])=><label key={name}><span>{name}</span><input type="number" step="any" value={value} onChange={e=>setValues({...values,[name]:Number(e.target.value)})}/></label>)}<button onClick={()=>run(false,true)} disabled={busy}>Run edited values</button></div>}<div className="live-pipeline">{stages.map((name,i)=><div className={stage===i&&busy?'running':stage>=i?'done':''} key={name}><i>{stage>=i?'✓':i+1}</i><span>{name}</span></div>)}</div>{result&&!result.error&&!busy&&<div className="stage-slider"><div>{views.map((name,i)=><button className={viewStage===i?'active':''} onClick={()=>setViewStage(i)} key={name}>{name}</button>)}</div><input aria-label="Explore analysis stage" type="range" min="0" max="4" value={viewStage} onChange={e=>setViewStage(Number(e.target.value))}/></div>}<output>{busy?<div className="running-result"><span/><strong>{stages[stage]}</strong><p>Processing notebook stage {stage+1} of {stages.length}</p></div>:!result?<div className="empty-result"><Bird/><strong>Ready to simulate</strong><p>Select any of the 657 dataset rows.</p></div>:result.error?<div className="error-result"><strong>Model service is offline</strong><p>{result.error}</p></div>:<StageView result={result} stage={viewStage}/>}</output></div><div className="tested"><h3>Notebook order</h3>{[['01','main.ipynb','Prepare + split'],['02','association.ipynb','Frequent rules'],['03','clustering.ipynb','Building profiles'],['04','classification.ipynb','Lower / Higher'],['05','regression.ipynb','Exact count'],['06','final_eval.ipynb','Holdout test']].map(([n,name,task])=><div key={name}><small>{n}</small><strong>{name}</strong><span>{task}</span></div>)}</div></div>
}

function StageView({result,stage}:{result:SimulationResult;stage:number}){
  const model=result.bestModels!; const rules=result.associationRules ?? [];
  const meta=<p className="record-meta"><b>Row {(result.position??0)+1}</b> of {result.totalRecords} · {result.building} · ID {result.id} · {result.split}</p>;
  if(stage===0)return <div className="stage-view">{meta}<h3>Dataset nature</h3><p>One row represents one building. ID groups buildings from the same survey location. The model uses seven building and environmental features.</p><div className="features">{Object.entries(result.record ?? {}).map(([name,value])=><div key={name}><span>{name}</span><b>{value}</b></div>)}</div><blockquote>{result.edited?'Edited values are synthetic, so no actual NestCount is available.':`This dataset record has an actual NestCount of ${result.actualNestCount}.`}</blockquote></div>;
  if(stage===1)return <div className="stage-view">{meta}<h3>Association knowledge</h3>{rules.length?rules.map(rule=><article key={rule.rule}><p>{rule.rule.replaceAll(' AND ',' + ').replace('NestCountGroup=','')}</p><small>Confidence {(rule.confidence*100).toFixed(1)}% · Lift {rule.lift}</small></article>):<p>No shortlisted positive rule matched this record.</p>}<blockquote>These conditions occur together in training data; they do not prove cause and effect.</blockquote></div>;
  if(stage===2)return <div className="stage-view">{meta}<h3>Clustering result</h3><strong className="big-result">Cluster {result.cluster}</strong><h4>{result.clusterProfile?.name}</h4><p>{result.clusterProfile?.characteristics}</p><small>{result.clusterProfile?.records} training records belong to this profile.</small><blockquote>The cluster describes similarity across seven standardized features. It is not a Lower or Higher prediction.</blockquote></div>;
  if(stage===3)return <div className="stage-view">{meta}<h3>Prediction result</h3><div className="result-summary"><article><span>Actual nests</span><strong>{result.edited?'N/A':result.actualNestCount}</strong></article><article><span>Estimated nests</span><strong>{model.estimatedCount}</strong></article><article><span>Predicted class</span><strong className="class-result">{model.class}</strong></article><article><span>Higher probability</span><strong>{Math.round(model.probability*100)}%</strong></article></div><blockquote>The saved Decision Trees provide an educational estimate. Holdout performance was weak.</blockquote></div>;
  return <div className="stage-view">{meta}<h3>Knowledge from this record</h3><ul><li>{result.edited?'No observed count exists for edited values.':`Actual count: ${result.actualNestCount}.`} Model estimate: {model.estimatedCount}.</li><li>Predicted class: {model.class} with {Math.round(model.probability*100)}% model probability.</li><li>Environmental profile: Cluster {result.cluster}, {result.clusterProfile?.name}.</li><li>{rules.length} shortlisted association rule{rules.length===1?'':'s'} matched.</li></ul><blockquote>Together, the methods describe co-occurrence, similarity and prediction. The holdout test determines how cautiously these results should be generalized.</blockquote></div>;
}
